### ISSUE TITLE
Checking arbitrary files doesn't work

### ISSUE THREAD

**Issue by clbr** [dlidstrom/Duplo#13]
It currently skips FILETYPE_UNKNOWN files. I'd like to use it on any arbitrary text file.

This patch seems to work:
```
diff --git a/SourceFile.cpp b/SourceFile.cpp
index 18b5a80..fb6082e 100755
--- a/SourceFile.cpp
+++ b/SourceFile.cpp
@@ -63,7 +63,8 @@ SourceFile::SourceFile(const std::string& fileName, const unsigned int minChars,
                 }
             }
         }
-        if (FileType::FILETYPE_VB == m_FileType) {
+        if (FileType::FILETYPE_VB == m_FileType ||^M
+            FileType::FILETYPE_UNKNOWN == m_FileType) {^M
             tmp = line;
         }

```

**Comment by dlidstrom** [comment]
Thanks, I will incorporate your suggestion when I get a chance. Probably sometime next week or so.

**Comment by dlidstrom** [comment]
I haven’t tried this patch myself, but you can easily apply it and build your own version. Then of course let me know how it works for you!

**Comment by mominmaaz** [comment]
I have build my own version. Works well. Thank you.

**Comment by dlidstrom** [comment]
Thanks for letting me know. I’ll merge this eventually.
