### ISSUE TITLE
Unique Duplicate LOC count

### ISSUE THREAD

**Issue by mominmaaz** [dlidstrom/Duplo#18]
I was doing some testing with Duplo. There is situation where my Total_lines_of_code is smaller than Duplicate_lines_of_code.

**Comment by mominmaaz** [comment]
<summary Num_files="179" Duplicate_blocks="42479" Total_lines_of_code="17856" Duplicate_lines_of_code="265970" Time="539.592"/>

**Comment by mominmaaz** [comment]
---xml 
summary --- Num_files="179" Duplicate_blocks="42479" Total_lines_of_code="17856" Duplicate_lines_of_code="265970" Time="539.592" ---

**Comment by dlidstrom** [comment]
Can you try to extract a sample where it counts wrong in just a single file?

**Comment by mominmaaz** [comment]
#include <iostream>
using namespace std;

void add()
{
	int firstNumber, secondNumber, sumOfTwoNumbers;
    
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;

    // sum of two numbers in stored in variable sumOfTwoNumbers
    sumOfTwoNumbers = firstNumber + secondNumber;

    // Prints sum 
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;
}

void add2()
{
	int firstNumber, secondNumber, sumOfTwoNumbers;
    
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;

    // sum of two numbers in stored in variable sumOfTwoNumbers
    sumOfTwoNumbers = firstNumber + secondNumber;

    // Prints sum 
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;
}

void add3()
{
	int firstNumber, secondNumber, sumOfTwoNumbers;
    
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;

    // sum of two numbers in stored in variable sumOfTwoNumbers
    sumOfTwoNumbers = firstNumber + secondNumber;

    // Prints sum 
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;
}

int main()
{
    int firstNumber, secondNumber, sumOfTwoNumbers;
    
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;

    // sum of two numbers in stored in variable sumOfTwoNumbers
    sumOfTwoNumbers = firstNumber + secondNumber;

    // Prints sum 
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;     

    return 0;
}

**Comment by mominmaaz** [comment]
Duplo.exe -ml 4 -xml inputfile.txt ouputfile.xml

inputfile.txt contains just the name of this file

**Comment by dlidstrom** [comment]
So I just tried this. Duplo is reporting 27 lines of code and 30 duplicate lines. I think the reason for this is easier to see without xml:

```txt
main.cpp(19)
main.cpp(5)
    int firstNumber, secondNumber, sumOfTwoNumbers;
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;
    sumOfTwoNumbers = firstNumber + secondNumber;
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;

main.cpp(33)
main.cpp(19)
    int firstNumber, secondNumber, sumOfTwoNumbers;
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;
    sumOfTwoNumbers = firstNumber + secondNumber;
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;

main.cpp(47)
main.cpp(33)
    int firstNumber, secondNumber, sumOfTwoNumbers;
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;
    sumOfTwoNumbers = firstNumber + secondNumber;
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;

main.cpp(33)
main.cpp(5)
    int firstNumber, secondNumber, sumOfTwoNumbers;
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;
    sumOfTwoNumbers = firstNumber + secondNumber;
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;

main.cpp(47)
main.cpp(19)
    int firstNumber, secondNumber, sumOfTwoNumbers;
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;
    sumOfTwoNumbers = firstNumber + secondNumber;
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;

main.cpp(47)
main.cpp(5)
    int firstNumber, secondNumber, sumOfTwoNumbers;
    cout << "Enter two integers: ";
    cin >> firstNumber >> secondNumber;
    sumOfTwoNumbers = firstNumber + secondNumber;
    cout << firstNumber << " + " <<  secondNumber << " = " << sumOfTwoNumbers;

Configuration: 
  Number of files: 1
  Minimal block size: 4
  Minimal characters in line: 3
  Ignore preprocessor directives: 0
  Ignore same filenames: 0

Results: 
  Lines of code: 27
  Duplicate lines of code: 30
  Total 6 duplicate block(s) found.

  Time: 0.002 seconds
```

Each duplicate code block is included in the duplicate lines count. I guess this is by design and I'm not sure how Duplo should count this in any other way?

**Comment by mominmaaz** [comment]
The main problem I face is I cannot take percentage of duplication in the files. 
Formula is very simple: Duplicate LOC  /  LOC *100

but if Duplication LOC goes above LOC then it'll report more than 100%. What do you advise here?

**Comment by dlidstrom** [comment]
I propose that you clamp the values like so:

```c++
100 * std::min(1, duplicateLines/lines);
```

Sorry, but since Duplo does not report this statistic I guess this is your best solution. Or choose another metric to report.
