### ISSUE TITLE
XML Output is broken

### ISSUE THREAD

**Issue by ArsMasiuk** [dlidstrom/Duplo#23]
There are no xml heading tags written into output.xml.
I'm suggesting the following change in Duplo.cpp in order to fix the issue:

```
@@ -350,6 +350,14 @@
     }
 
     std::cout << "Loading and hashing files ... " << std::flush;
+
+    if (options.GetOutputXml()) {
+        outfile
+            << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
+            << std::endl
+            << "<duplo>"
+            << std::endl;
+    }
 
     auto lines = LoadFileList(options.GetListFilename());
     auto [sourceFiles, matrix, files, locsTotal] =
```

P.S. Thank you for the great software :)

**Comment by dlidstrom** [comment]
I am not sure the xml can be considered broken. Do you have an actual issue where the xml can’t be used as-is? Can you provide a screenshot perhaps?
I believe the xml is well-formed, see [w3.org specification](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-prolog-dtd). Also, I don’t think I can specify utf-8, as there is no specific handling of text encoding. I could perhaps add the xml version though, if this helps resolve your issue.
Thanks for using Duplo and providing feedback!

**Comment by ArsMasiuk** [comment]
Well, I mean the following issue: the xml output currently looks like:

```
  ...
   <set LineCount="21">
        <block SourceFile="..." StartLineNumber="267"/>
        <block SourceFile="..." StartLineNumber="222"/>
        <lines xml:space="preserve">
            <line Text="..."/>
               ...
            <line Text="..."/>
        </lines>
    </set>
   ...
</duplo>
```

So there is closing tag **&lt;/duplo&gt;** at the very end, but there is no corresponding opening tag **&lt;duplo&gt;** at the beginning of the document. Therefore this xml cannot be read by some xml parsers. 
The tag &lt;?xml ... ?&gt; would be also nice-to-have as it _could_ be important for some of them.

**Comment by dlidstrom** [comment]
You are right! As you already have the fix, can you provide a PR? Without the encoding part:

```xml
<?xml version="1.0"?>
<duplo>
```
