### ISSUE TITLE
Why multiple duplicates hasn't been merged?

### ISSUE THREAD

**Issue by faywong** [dlidstrom/Duplo#25]
for example:

file_a.c line 100 duplicates to file_a.c line 200 and file_a.c line 500 and  file_a.c line 600, expecte the result to be 

file_a.c line 100 file_a.c line 200 file_a.c 500 are duplicated other than:

line 100 duplicates to line 200, line 500 duplicates to line 600.

**Comment by dlidstrom** [comment]
I am not sure exactly why this happens. Does this cause an issue for you? I guess no, since the program found all cases of duplication, right?

**Comment by ArsMasiuk** [comment]
> for example:
> 
> file_a.c line 100 duplicates to file_a.c line 200 and file_a.c line 500 and file_a.c line 600, expecte the result to be
> 
> file_a.c line 100 file_a.c line 200 file_a.c 500 are duplicated other than:
> 
> line 100 duplicates to line 200, line 500 duplicates to line 600.

Do you mean that the program says nothing about line 600 in the output?

**Comment by faywong** [comment]
I mean duplicate lines maybe should be expressed as:

```json
“duplicated content": [all the occurences, such as "file1:1"， "file2:2" , "file3:4" ... ]
```

**Comment by ArsMasiuk** [comment]
> I mean duplicate lines maybe should be expressed as:
> 
> ```json
> “duplicated content": [all the occurences, such as "file1:1"， "file2:2" , "file3:4" ... ]
> ```

Well I'm currently (slow) working on a GUI frontend for Duplo: https://github.com/ArsMasiuk/duploq
The tool tries to aggregate Duplo's output as well, hope that's what you are talking about?

**Comment by dlidstrom** [comment]
Good suggestion @faywong . I’ll think a bit about this, but can’t promise anything as of now.

**Comment by faywong** [comment]
> > I mean duplicate lines maybe should be expressed as:
> > ```json
> > “duplicated content": [all the occurences, such as "file1:1"， "file2:2" , "file3:4" ... ]
> > ```
> 
> Well I'm currently (slow) working on a GUI frontend for Duplo: https://github.com/ArsMasiuk/duploq
> The tool tries to aggregate Duplo's output as well, hope that's what you are talking about?

Cool, aggregate Duplo's output in a post-process step is also a good solution. Also i have opt. the algorithm to boost the performance.

**Comment by dlidstrom** [comment]
@faywong cool, is that something you can share?

**Comment by faywong** [comment]
> @faywong cool, is that something you can share?

Currently is only capable of use in our case, hasn't reach the expected performance yet.  Anyway, i will update here if we're ready to contribute a better version.

**Comment by dlidstrom** [comment]
In the spirit of open source and all future users of Duplo, please do.

**Comment by DanielLidstromTicket** [comment]
@faywong Is there something you can share with your implementation?

**Comment by dlidstrom** [comment]
@faywong Is there something you can share with your implementation?
